name: .NET Framework CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        run: |
          choco install dotnetfx --version=4.7.2.20180712 -y
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv

      - name: Restore dependencies
        run: nuget restore

      - name: Build
        run: dotnet build

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Framework
        run: |
          choco install dotnetfx --version=4.7.2.20180712 -y
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv

      - name: Run Tests
        run: |
          testFiles=$(Get-ChildItem ./src/PayloadTests -Filter *.cs)

          for testFile in $testFiles; do
            echo "Running tests in $testFile"
            dotnet test ./src/PayloadTests/PayloadTests.csproj --filter "FullyQualifiedName~$testFile"
          done
