name: .NET Framework CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Framework
        run: |
          choco install dotnetfx --version=4.7.2.20180712 -y
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv

      - name: Restore dependencies
        run: nuget restore ../../src/PayloadTests/PayloadTests.csproj

      - name: Build
        run: msbuild /p:Configuration=Release

      - name: Test
        run: |
          nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
          testrunner/NUnit.Console.3.12.0/tools/nunit3-console.exe Test*.cs
